variables:
  SERVER_IP: "18.139.227.254" # Thay YOUR_SERVER_IP bằng địa chỉ IP của server Lightsail
  SERVER_USER: "root" # Thay YOUR_SERVER_USER bằng tên người dùng SSH trên server Ubuntu
  IMAGE_NAME: "phamminhman10/demo-gitlab-cicd"
  IMAGE_TAG: "v1.0"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - ifconfig
    - docker ps -a
    - docker login -u phamminhman10 -p dckr_pat_MdBJxn5WRrYGUPzzqLr88M3BIUE
  script:
    - docker build -t $IMAGE_NAME:v1.0
    - docker push $IMAGE_NAME:v1.0.0


# build:
#   stage: build
#   script:
#     - apt update && apt install -y curl
#     - curl -sL https://deb.nodesource.com/setup_16.x | bash -
#     - apt update && apt -y install nodejs
#     - npm install # Cài đặt các gói NodeJS

# deploy:
#   stage: deploy
#   script:
#     - apt update && apt-get -y install openssh-server # Cài đặt sshpass để truy cập SSH bằng mật khẩu (tùy chọn)
#     - echo "$SSH_PRIVATE_KEY" > key.pem
#     - chmod 600 key.pem
#     - ssh -T root@18.139.227.254

