version: '3'
services:
  nodejs1:
    image: phamminhman10/base-nestjs:v4
    container_name: nodejs_server1
    environment:
      - name=server1
    # ports:
      # - 3000:3000
    networks:
      - my_network
  
  nodejs2:
    image: phamminhman10/base-nestjs:v4
    container_name: nodejs_server2
    environment:
      - name="server2"
    # ports:
      # - 3001:3000
    networks:
      - my_network

  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx_server
    # command: sh -c "apk update && apk add bash && apk add curl && apk add apache2-utils"
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"

networks:
  my_network:
    driver: bridge
